#!/bin/bash

./qwirkle.exe e2etest < ./tests/tile-colours/test.input > ./qwirkle.out;
if diff -w ./tests/tile-colours/test.output ./qwirkle.out; then
    echo "Test passed";
else
    echo "Test failed";
fi