#!/bin/bash

./qwirkle.exe e2etest < ./tests/multi-tile-play/test.input > ./qwirkle.out
if diff -w ./tests/multi-tile-play/test.output ./qwirkle.out; then
    echo "Test passed"
else
    echo "Test failed"
fi